### ISSUE TITLE
Connect problem

### ISSUE THREAD

**Issue by pidiman** [deuteros76/meteo-home#1]
Hello 

I have problem with connection. I uploaded your sketch and then connected to meteo-home ap.

I was saved correct wifi SSID and password but my meteo station wrote : Cannot connect and then I was saw meteo-home AP again :(

I was tried everything, combination of IP adress, network_ip = "0.0.0.0", reserved IP and MAC adress...

Can you help me? Thanks

**Comment by deuteros76** [comment]
Hi

You have to set a right IP addres and port.  Chek your router configuration also.
